<?php

Class PartidoTableSeeder extends Seeder {

	public function run() {
	//	DB::table('partidos')->delete();

	$partidos = [
		//la fecha se introduce como mes/dia/año horas:min:segs
		//estados: 1 (oculto), 2 (publico), 3 (aplazado)
		/************************** LIGA BBVA 2014 ************************************/
		/* ====================== JORNADA 1 =================================== */
		['estado' => 2,'equipo_local_id' => 13, 'equipo_visitante_id' => 19, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d', strtotime('08/25/2014 20:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "1-0 Benzema(30'), 2-0 C. Ronaldo(90')", 'descripcion_v' => '', 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 12, 'equipo_visitante_id' => 2, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/25/2014 22:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => '', 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 6, 'equipo_visitante_id' => 14, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/24/2014 19:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "1-0 Javi Lara(19')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 3, 'equipo_visitante_id' => 20, 'puntos_equipo_l' => 3, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/24/2014 21:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "1-0 Messi(42'), 2-0 Munir(46'), 3-0 Messi(63')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 4, 'equipo_visitante_id' => 8, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/24/2014 21:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "1-0 Nolito(20'), 2-0 Orellana(52'), 3-1 Larryvei(70')", 'descripcion_v' => "2-1 Sammir(62')", 'descripcion_p' => ''],
		['estado' => 2,'equipo_local_id' => 10, 'equipo_visitante_id' => 17, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/24/2014 23:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => '', 'descripcion_v' => "0-1 Uche(54'), 0-2 Cheryshev (85')", 'descripcion_p' => ''],
		['estado' => 2,'equipo_local_id' => 11, 'equipo_visitante_id' => 1, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2014 19:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "0-1 Luis Alberto(35')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 15, 'equipo_visitante_id' => 16, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2014 21:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "0-1 Aleix Vidal(44')", 'descripcion_v' => "1-1 Orbán(88')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 9, 'equipo_visitante_id' => 5, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2014 21:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "1-1 Rochina(54'), 2-1 Babin(77')", 'descripcion_v' => "0-1 Cavaleiro (20')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 18, 'equipo_visitante_id' => 7, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2014 23:00:00')), 'jornada_id' => 1, 'grupo_id' => 1, 'descripcion_l' => "1-0 Soriano(52')", 'descripcion_v' => "1-1  Sergio García(103')", 'descripcion_p' => ''], 

		/* ====================== JORNADA 2 =================================== */
/*11*/	['estado' => 2,'equipo_local_id' => 14, 'equipo_visitante_id' => 13, 'puntos_equipo_l' => 4, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/31/2014 21:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "1-2 Iñigo Martínez(35'), 2-2 Zurutuza(41'), 3-2 Zurutuza(65'), 4-2 Carlos Vela(75')", 'descripcion_v' => "0-1 Sergio Ramos(5'), 0-2 Bale(11')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 5, 'equipo_visitante_id' => 12, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/31/2014 21:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "1-0 José Rodríguez(7'), 2-2 Cuenca, p.(94')", 'descripcion_v' => "1-1 Bueno(40'), 1-2 Bueno(73')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 20, 'equipo_visitante_id' => 9, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/31/2014 23:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "1-1 Lombán(91')", 'descripcion_v' => "0-1 Fran Rico(81')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 3, 'equipo_visitante_id' => 17, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/31/2014 19:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => '', 'descripcion_v' => "0-1 Sandro Ramírez(82')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 8, 'equipo_visitante_id' => 18, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/29/2014 20:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "0-1 Álvaro Vázquez(29')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 16, 'equipo_visitante_id' => 11, 'puntos_equipo_l' => 3, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/29/2014 22:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "0-1 Paco Alcácer(31'), 0-2 Parejo(45'), 0-3 Piatti(56')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 16, 'equipo_visitante_id' => 11, 'puntos_equipo_l' => 3, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2014 19:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "01 Aduriz(32'), 0-2 Iturraspe(51'), 0-3 Muniain(76')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 19, 'equipo_visitante_id' => 4, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2014 19:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "1-1 Fede Cartabia(59')", 'descripcion_v' => "0-1 Orellana(52')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 2, 'equipo_visitante_id' => 6, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2014 21:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "1-0 Miranda(11'), 2-0 Mandzukic(25')", 'descripcion_v' => "2-1 Abraham(33')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 7, 'equipo_visitante_id' => 15, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2014 21:00:00')), 'jornada_id' => 2, 'grupo_id' => 1, 'descripcion_l' => "1-2 Stuani(61'), 2-0 Mandzukic(25')", 'descripcion_v' => "0-1 Bacca(33'), 0-2 Iborra(56')", 'descripcion_p' => '']
		];

	DB::table('partidos')->insert($partidos);

	$partidos = [	
		/************************** LIGA ACB 2014 ************************************/
		/* ====================== JORNADA 1 =================================== */
/*21*/	['estado' => 2,'equipo_local_id' => 28, 'equipo_visitante_id' => 35, 'puntos_equipo_l' => 87, 'puntos_equipo_v' => 96, 'fecha_hora' => date('Y-m-d', strtotime('10/04/2014 20:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '(24+21+30+12): Radicevic (5), Urtasun (21), Byars (6), Porzingis (3), Hernangómez (16) -cinco inicial-, Thames (8), Oriola (11), Berni Rodríguez (5), Pullen (10) y Balvin (2).', 'descripcion_v' => '(28+27+21+20): Úriz (5), Richotti (12), Sikma (23), Beirán (13), Sekulic (15) -cinco inicial-, Tsairelis (5), Rost (10), San Miguel (9), Heras (-) y Lampropoulos (4).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 42, 'equipo_visitante_id' => 37, 'puntos_equipo_l' => 88, 'puntos_equipo_v' => 64, 'fecha_hora' => date('Y-m-d', strtotime('10/04/2014 20:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '(26+17+26+19): Pepe Pozas (11), Pavel Pumprla (11), Alberto Corbacho (8), Maxi Kleber (18), Juanjo Triguero (12) -cinco inicial-, Daniel Miller (2), Adam Waczynski (7), Fran Cárdenas (7), Haris Giannopoulos (3), Jesús Chagoyen (4) y Keaton Nankivil (5).', 'descripcion_v' => '(13+12+16+23): Nil Angelats (-), Marius Grigonis (2), Ben Dewar (3), Jamar Samuels (5), AJ Ogilvy (12) -cinco inicial-, Michael Hall (7), Carles Bivià (15), Marc García (3), Roger Grimau (14) y Dimitris Haritopoulos (3).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 31, 'equipo_visitante_id' => 36, 'puntos_equipo_l' => 87, 'puntos_equipo_v' => 65, 'fecha_hora' => date('Y-m-d', strtotime('10/04/2014 21:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => ' (24+21+13+29): Huertas (13), Navarro (13), Thomas (-), Doellman (9), Tomic (11) -cinco inicial-, Oleson (7), Abrines (18), Nachbar (3), Pleiss (12), Lampe (-), Hezonja (1) y Eriksson (-).', 'descripcion_v' => '(12+25+12+16): Heurtel (4), Johnson (12), Bertrans (24), Tillie (10), Iverson (2) -cinco inicial-, I.Diop (-), Gomes (2), San Emeterio (11), Causeur (-) y Perkins (-).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 30, 'equipo_visitante_id' => 38, 'puntos_equipo_l' => 73, 'puntos_equipo_v' => 54, 'fecha_hora' => date('Y-m-d', strtotime('10/05/2014 21:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => 'Colom (7), Bertans (9), M. Todorovic (8), Mumbrú (7), Hervelle (17) –cinco inicial- Mendía (2), Borg (-), D. Todorovic (-), Williams (7), Raúl López (5), Andjusic (11).', 'descripcion_v' => 'Alberto Díaz (-), Baron (13), Clark (7), Panko (14), Diagné (4) –cinco inicial- Pérez (-), Vega (4), Akindele (10), Papamakarios (-), Miso (2), Rolands Smits (-).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 43, 'equipo_visitante_id' => 45, 'puntos_equipo_l' => 85, 'puntos_equipo_v' => 76, 'fecha_hora' => date('Y-m-d', strtotime('10/05/2014 12:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '(18+26+29+12): Cabezas (7), Neto (13), Kelati (4), Antelo (18) y Lima (22) -cinco inicial-, Radovic (9), Wood (8) y Rojas (4).', 'descripcion_v' => '(27+18+13+18): Van Rossom (10), Rafa Martínez (-), Lucic (10), Aguilar (15) y Loncar (6) -cinco inicial-, Ribas (12), Sato (4), Lishchuk (8), Vives (1), Buycks (1) y Harangody (9).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 41, 'equipo_visitante_id' => 39, 'puntos_equipo_l' => 70, 'puntos_equipo_v' => 57, 'fecha_hora' => date('Y-m-d', strtotime('10/05/2014 13:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '', 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 44, 'equipo_visitante_id' => 34, 'puntos_equipo_l' => 83, 'puntos_equipo_v' => 69, 'fecha_hora' => date('Y-m-d', strtotime('10/05/2014 18:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '(19+19+19+26): Markovic (2), Toolson (18), Kuzminskas (2) Thomas (12), Vázquez (20) -cinco inicial-, Vasileiadis (6), Nguirane (-), Granger (6), Suárez (4), Stefansson (4), Golubovic (9) y Green (-).', 'descripcion_v' => '(15+18+17+19): Sada (6), Navarro (3), Gomes (23), Bogris (2), Ivanov (10) -cinco inicial-, Schreiner (3), Trias (4), Green (9), Martínez (-) y Blanch (9).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 29, 'equipo_visitante_id' => 32, 'puntos_equipo_l' => 74, 'puntos_equipo_v' => 79, 'fecha_hora' => date('Y-m-d', strtotime('10/05/2014 20:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '(15+21+20+18): Lich (13), Goulding (4), Pere Tomás (-), Landry (9), Norel (12) -cinco inicial- Llompart (4), Katic (10), Sastre (5), Robinson (4) y Jelovac (13).', 'descripcion_v' => '(19+14+17+29): Mallet (13), Ventura (5), Kirksay (8), Suárez (-), Miralles (12) -cinco inicial- Sergi Vidal (8), Hannah (15), Suton (18), Abalde (-) y Barrera (-).', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 40, 'equipo_visitante_id' => 33, 'puntos_equipo_l' => 91, 'puntos_equipo_v' => 74, 'fecha_hora' => date('Y-m-d', strtotime('10/05/2014 19:00:00')), 'jornada_id' => 39, 'grupo_id' => 2, 'descripcion_l' => '(22+25+22+22): Salgado (14), Rabaseda (7), Hernangómez (-), Martín (16), Simpson (15) -cinco inicial-, Bircevic (9), Fernández (13), Ortega (-), Nunnally (17) y Martínez (-).', 'descripcion_v' => '(27+8+27+12): Jordan (15), Dean (11), Díez (18), Hanley (7), Doblas (12) -cinco inicial-, Iarochevitch (11), Franch (-), Olaizola (-), Grimau (-), Motos (-) y Huskic (-).', 'descripcion_p' => '']
		];
	DB::table('partidos')->insert($partidos);

		/************************** Premier League 2015  ************************************/
	$partidos = [
		/* ====================== JORNADA 1 (111)=================================== */
/*30*/	['estado' => 2,'equipo_local_id' => 46, 'equipo_visitante_id' => 47, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d', strtotime('08/08/2015 13:45:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "K. Walker (22') ", 'descripcion_v' => '', 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 48, 'equipo_visitante_id' => 49, 'puntos_equipo_l' => 4, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d', strtotime('08/08/2015 16:00:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "J. Vardy (11'), R. Mahrez (18'), R. Mahrez (24'), M. Albrighton (66') ", 'descripcion_v' => "J. Defoe (61'), S. Fletcher (71')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 50, 'equipo_visitante_id' => 51, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 3, 'fecha_hora' => date('Y-m-d', strtotime('08/08/2015 16:00:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "N. Redmond (69')", 'descripcion_v' => "W. Zaha (39'), D. Delaney (50'), Y. Cabaye (90')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 52, 'equipo_visitante_id' => 53, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d', strtotime('08/08/2015 16:00:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "R. Barkley (76'), A. Koné (85')", 'descripcion_v' => "M. Layún (14'), O. Ighalo (83')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 54, 'equipo_visitante_id' => 55, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d', strtotime('08/08/2015 16:00:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "", 'descripcion_v' => "R. Gestede (72')", 'descripcion_p' => ''] ,

		['estado' => 2,'equipo_local_id' => 56, 'equipo_visitante_id' => 57, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d', strtotime('08/08/2015 18:30:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "Oscar (23'), F. Fernández (30')", 'descripcion_v' => "A. Ayew (28'), B. Gomis (55')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 58, 'equipo_visitante_id' => 59, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d', strtotime('08/09/2015 14:30:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "P. Cissé (43'), G. Wijnaldum (48')", 'descripcion_v' => "G. Pellè (25'), S. Long (79')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 60, 'equipo_visitante_id' => 61, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d', strtotime('08/09/2015 14:30:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "", 'descripcion_v' => "C. Kouyaté (44') Goles M. Zárate (57')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 62, 'equipo_visitante_id' => 63, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d', strtotime('08/09/2015 17:00:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "", 'descripcion_v' => "P. Coutinho (85')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 64, 'equipo_visitante_id' => 65, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 3, 'fecha_hora' => date('Y-m-d', strtotime('08/09/2015 17:00:00')), 'jornada_id' => 111, 'grupo_id' => 4, 'descripcion_l' => "", 'descripcion_v' => "Y. Touré (9'), Y. Touré (24'), V. Kompany (59')", 'descripcion_p' => ''] 
		];
	DB::table('partidos')->insert($partidos);

	$partidos = [
		/************************** LIGA BBVA 2015 ************************************/
		/* ====================== JORNADA 1 (73)=================================== */
/*40*/	['estado' => 2,'equipo_local_id' => 11, 'equipo_visitante_id' => 15, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d', strtotime('08/21/201 20:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "", 'descripcion_v' => '', 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 5, 'equipo_visitante_id' => 14, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/22/2015 18:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => '', 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 7, 'equipo_visitante_id' => 8, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/22/2015 18:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "Salva Sevilla (3')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 2, 'equipo_visitante_id' => 21, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/22/2015 20:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "A. Griezmann (16')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 12, 'equipo_visitante_id' => 16, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/22/2015 22:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => '', 'descripcion_v' => '', 'descripcion_p' => ''],
		['estado' => 2,'equipo_local_id' => 1, 'equipo_visitante_id' => 3, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2015 18:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => '', 'descripcion_v' => " L. Suárez (54')", 'descripcion_p' => ''],
		['estado' => 2,'equipo_local_id' => 22, 'equipo_visitante_id' => 13, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2015 20:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "0-1 Luis Alberto(35')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 10, 'equipo_visitante_id' => 4, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2015 22:00:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "Verza (55')", 'descripcion_v' => "F. Orellana (41'), Iago Aspas (77')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 23, 'equipo_visitante_id' => 17, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/23/2015 22:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "Rubén Castro (87')", 'descripcion_v' => "R. Soldado (31')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 9, 'equipo_visitante_id' => 6, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 3, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/24/2015 20:30:00')), 'jornada_id' => 73, 'grupo_id' => 3, 'descripcion_l' => "R. Rochina (49')", 'descripcion_v' => "Adrián (22'), G. Escalante (34'), Arruabarrena (66')", 'descripcion_p' => ''],

		/* ====================== JORNADA 2 =================================== */
		['estado' => 2,'equipo_local_id' => 17, 'equipo_visitante_id' => 7, 'puntos_equipo_l' => 3, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d', strtotime('08/28/2015 20:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "R. Soldado(67'), C. Bakambu (87'), C. Bakambu (93') ", 'descripcion_v' => "F. Caicedo (5')", 'descripcion_p' => ''] ,
		['estado' => 2,'equipo_local_id' => 14, 'equipo_visitante_id' => 22, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/29/2015 18:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => '', 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 3, 'equipo_visitante_id' => 11, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/29/2015 20:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "T. Vermaelen (73')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 4, 'equipo_visitante_id' => 12, 'puntos_equipo_l' => 3, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/29/2015 22:00:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "Nolito (11'), Nolito (49'), A. Fontàs (88')", 'descripcion_v' => '', 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 13, 'equipo_visitante_id' => 23, 'puntos_equipo_l' => 5, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/29/2015 22:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "G. Bale (2'), James (38'), K. Benzema (46'), James (49'), G. Bale (89') ", 'descripcion_v' => '', 'descripcion_p' => ''],
		['estado' => 2,'equipo_local_id' => 6, 'equipo_visitante_id' => 1, 'puntos_equipo_l' => 2, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2015 18:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "Saúl (34'), Adrián (61')", 'descripcion_v' => "", 'descripcion_p' => ''],
		['estado' => 2,'equipo_local_id' => 16, 'equipo_visitante_id' => 5, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 1, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2015 20:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "Á. Negredo (45')", 'descripcion_v' => "Lucas (39')", 'descripcion_p' => "Expulsión de Barragán(84')"], 
		['estado' => 2,'equipo_local_id' => 15, 'equipo_visitante_id' => 2, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 3, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2015 20:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "", 'descripcion_v' => "Koke (35'), Gabi (78'), J. Martínez (85')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 8, 'equipo_visitante_id' => 9, 'puntos_equipo_l' => 1, 'puntos_equipo_v' => 2, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2015 22:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "Lafita (80')", 'descripcion_v' => "Y. El-Arabi (26'), I. Success (29')", 'descripcion_p' => ''], 
		['estado' => 2,'equipo_local_id' => 21, 'equipo_visitante_id' => 10, 'puntos_equipo_l' => 0, 'puntos_equipo_v' => 0, 'fecha_hora' => date('Y-m-d H:i:s', strtotime('08/30/2015 22:30:00')), 'jornada_id' => 74, 'grupo_id' => 3, 'descripcion_l' => "R. Rochina (49')", 'descripcion_v' => "", 'descripcion_p' => '']
		];
	DB::table('partidos')->insert($partidos);

	}
}